services:
    web:
        build: .
        command: >
            sh -c "python manage.py makemigrations  &&
                python manage.py migrate &&
                python manage.py collectstatic --noinput && 
                gunicorn config.wsgi:application --bind 0.0.0.0:8000"
        ports:
              - "8000:8000"
        restart: always
        env_file:
            - .env
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
        depends_on:
            - db
            - redis
        networks:
            - app_network
    db:
        hostname: db
        image: postgres:17
        container_name: db_library
        env_file:
            - ./.env
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network
    redis:
        image: redis:7
        ports:
            - "6379:6379"
        env_file:
            - ./.env
        volumes:
            - redis_data:/data
        networks:
            - app_network
    nginx:
        build:
          context: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - static_volume:/app/staticfiles
        depends_on:
            - web
            - redis
        networks:
            - app_network
networks:
    app_network:
        driver: bridge
volumes:
    postgres_data:
    static_volume:
    redis_data:
