# Generated by Django 5.2.3 on 2025-06-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0001_initial"),
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="book",
            field=models.ForeignKey(
                help_text="Выберите книгу",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental",
                to="library.book",
                verbose_name="Книга",
            ),
        ),
    ]
