# Generated by Django 5.2.3 on 2025-06-22 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0003_alter_book_quantity"),
        ("rental", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="book",
            field=models.ForeignKey(
                default=1,
                help_text="Выберите книгу",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental",
                to="library.book",
                verbose_name="Книга",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="user",
            field=models.ForeignKey(
                help_text="Выберите пользователя",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="rental",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
